required = [
  "k8s.io/apimachinery/pkg/util/sets/types",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "github.com/knative/caching/pkg/apis/caching",
  "github.com/knative/test-infra/scripts",
  "github.com/knative/test-infra/tools/dep-collector",
]

[[override]]
  name = "github.com/tektoncd/pipeline"
  revision = "c6a10130972ca3f9ae8ef0483da6f9fd7ad0d6c3"

[[override]]
  name = "gopkg.in/yaml.v2"
  version = "v2.2.1"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.6"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.6"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.12.6"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.6"

[[override]]
  name = "golang.org/x/sys"
  revision = "1c9583448a9c3aa0f9a6a5241bf73c0bd8aafded"  

[[override]]
  name = "github.com/json-iterator/go"
  # This is the commit at which k8s depends on this in 1.11
  # It seems to be broken at HEAD.
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"

[[override]]
  name = "github.com/google/go-containerregistry"
  # HEAD as of 2019-03-20
  revision = "8d4083db9aa0d2fae6588c1acdbe6a1f5db461e3"

[[override]]
  name = "github.com/golang/protobuf"
  # Lock the version of protobuf to keep things building.
  revision = "aa810b61a9c79d51363740d207bb46cf8e620ed5"

[[constraint]]
  name = "github.com/knative/caching"
  # HEAD as of 2019-03-21
  revision = "3fc06fd3c9880a9ebb5c401f4b20cf6666cc7bc0"

[[override]]
  name = "github.com/knative/pkg"
  # HEAD as of 2019-03-21 💖
  revision = "60fdcbcabd2faeb34328d8b2725dc76c59189453"

[[override]]
  name = "github.com/census-instrumentation/opencensus-proto"
  version = "v0.1.0"
  
[[override]]
  name = "go.uber.org/zap"
  revision = "67bc79d13d155c02fd008f721863ff8cc5f30659"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
